# Generated by Django 4.0.6 on 2022-10-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='item_pic'),
        ),
    ]
