# Generated by Django 4.0.6 on 2022-10-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
