# Generated by Django 4.0.6 on 2022-10-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_description_item_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Description',
            new_name='description',
        ),
    ]
