# Generated by Django 4.0.6 on 2022-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'shirt'), ('sport', 'sport'), ('outwears', 'outwears')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
