# Generated by Django 4.0.6 on 2022-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('NEW', 'new'), ('ON SALE', 'sale')], max_length=7, null=True),
        ),
    ]
