# Generated by Django 4.0.6 on 2023-01-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic'),
        ),
    ]
