# Generated by Django 4.0.6 on 2023-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_item_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='item_pic'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='item_pic'),
        ),
    ]
