# Generated by Django 4.0.6 on 2023-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wish',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
