# Generated by Django 4.0.6 on 2023-03-24 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_item_wish_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wish',
        ),
        migrations.AddField(
            model_name='item',
            name='wish',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
